version: '3.4'
services:
  server:
    image: postgrest/postgrest:v5.1.0
    container_name: swarmrest_server
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
    restart: unless-stopped
    depends_on:
      - db
  stats_facade:
    image: tomsaleeba/swarm-rest-metrics-facade:2.1.0
    container_name: swarmrest_stats_facade
    links:
      - server:server
      - elk:elk
    environment:
      TARGET_URL: http://server:3000
      ES_URL: http://elk:${ES_PORT}
      INDEX_NAME: ${ES_INDEX_NAME}
    restart: unless-stopped
    depends_on:
      - server
      - elk
  filter_proxy:
    image: tomsaleeba/nginx-filter-proxy:1.3.0
    container_name: swarmrest_filter_proxy
    links:
      - stats_facade:stats_facade
    ports:
      - "${EXTERNAL_LISTEN_PORT}:80"
      - "3000:80" # deprecated, remove once all users of ausplotsR have upgraded
    environment:
      TARGET_SERVER: 'stats_facade:80'
      DNS_NAME: ${PUBLIC_DNS_NAME}
    restart: unless-stopped
    depends_on:
      - stats_facade
  db:
    image: postgres:10
    container_name: swarmrest_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      RO_USER_NAME: ${DB_READONLY_USER}
      RO_USER_PASS: ${DB_READONLY_PASS}
    restart: unless-stopped
    volumes:
      - "swarm-pgdata:/var/lib/postgresql/data"
      - "./postgres/add-readonly-user.sh:/docker-entrypoint-initdb.d/add-readonly-user.sh"
  elk:
    image: sebp/elk:642
    container_name: swarmrest_elk
    ports:
      - "${KIBANA_PORT}:5601"
      - "${ES_PORT}:9200"
    environment:
      - LOGSTASH_START=0 # we don't need LogStash
      - AWS_ACCESS_KEY # override in shell at deploy time
      - AWS_SECRET # override in shell at deploy time
      - AWS_BUCKET=${S3_BUCKET}
      - ES_SNAPSHOT_REPO
      - KIBANA_CONNECT_RETRY=60 # the default 30 seconds doesn't seem long enough
    restart: unless-stopped
    healthcheck:
      test: curl -f localhost:9200/_cluster/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 1
      start_period: 99s
    volumes:
      - "elk-data:/var/lib/elasticsearch"
      - "./elk-pre-hook.sh:/usr/local/bin/elk-pre-hooks.sh"
      - "./elk-post-hook.sh:/usr/local/bin/elk-post-hooks.sh"
  autoheal: # thanks https://stackoverflow.com/a/48538213/1410035
    image: willfarrell/autoheal
    container_name: swarmrest_autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  es_snapshot:
    build: ./es-snapshot
    container_name: swarmrest_es_backup
    links:
      - elk:elk
    environment:
      ES_HOST: elk
      ES_PORT: ${ES_PORT}
      ES_SNAPSHOT_REPO: ${ES_SNAPSHOT_REPO}
      BACKUP_PREFIX: ${ES_SNAPSHOT_PREFIX}
      CRON_SCHEDULE: ${ES_SNAPSHOT_CRON_SCHEDULE}
    restart: unless-stopped
    depends_on:
      - elk
  db_sync:
    build: ./db-sync
    container_name: swarmrest_db_sync
    links:
      - db:db
    environment:
      FROM_USER: ${SWARM_PROD_USER}
      FROM_PASS: ${SWARM_PROD_PASS}
      FROM_HOST: ${SWARM_PROD_HOST}
      FROM_PORT: ${SWARM_PROD_PORT}
      FROM_DB: ${SWARM_PROD_DB}
      TO_USER: ${DB_USER}
      TO_PASS: ${DB_PASSWORD}
      TO_HOST: db
      TO_PORT: 5432
      TO_DB: ${DB_NAME}
      CRON_SCHEDULE: ${DB_SYNC_CRON_SCHEDULE}
    restart: unless-stopped
    depends_on:
      - db
volumes:
  elk-data:
  swarm-pgdata:

