version: '3'
services:
  nginx_filter_proxy:
    image: ternandsparrow/nginx-filter-proxy:2.1.1 # TODO might need to update version tag
    links:
      - stats_facade:stats_facade
    ports:
      - 30000:80
    environment:
      TARGET_SERVER: 'stats_facade:80'
      DNS_NAME: some.host # should be your "real" DNS name when deployed
  stats_facade:
    build: ..
    links:
      - es:es
    environment:
      TARGET_URL: http://swarmapi.ausplots.aekos.org.au # using live service, could also define a server in this stack
      ES_URL: es:9200
      INDEX_NAME: swarm-rest
    restart: unless-stopped
    depends_on:
      - es
  es:
    image: elasticsearch:6.5.1
    ports:
      - 9200:9200
    restart: unless-stopped
  kibana:
    image: kibana:6.5.1
    ports:
      - 5601:5601
    links:
      - es:es
    environment:
      ELASTICSEARCH_URL: http://es:9200
    restart: unless-stopped
