name: Run linting and stuff

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-md-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies and lint
      run: |
        cd ./ausplots-metadata-dictionary-server/
        yarn install --frozen-lockfile
        yarn lint
