name: Run linting and stuff

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-md-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
